### ISSUE TITLE
Paper.cpp error

### ISSUE THREAD

**Issue by evinpinar** [hanseuljun/temporal-rvl#2]
When I run the paper.cpp, I encounter 8 errors. Would it be because of gcc version mismatch?

./rvl.h:109:15: error: no matching conversion for functional-style cast from 'const char [56]' to 'std::exception'
        throw std::exception("RVL compression failed to reduce the size of its input.");

./trvl.h:56:32: error: extra qualification on member 'encode'
    std::vector<char> Encoder::encode(short* depth_buffer, bool keyframe)

paper.cpp:65:35: error: no member named 'filesystem' in namespace 'std'
    for (const auto& entry : std::filesystem::directory_iterator(folder_path)) {

paper.cpp:82:15: error: no matching conversion for functional-style cast from 'const char [26]' to 'std::exception'
        throw std::exception("The filename was invalid.");

paper.cpp:93:12: error: no matching constructor for initialization of 'InputFile'
    return InputFile(filename, std::move(input), width, height);

**Comment by hanseuljun** [comment]
Oh... I didn't know that the std::exception constructor with a string as a parameter was a MSVC extension... I think that is the problem. The way to fix this would be using std::runtime_error instead of std::exception. The same for the third one.

I think (or hope) other two are from this issue, and will update the repository to use std::runtime_error instead...
